feat: add terminal formatter
Colonial-Dev/inkjet pull request #23
Opened 2024-09-05 22:18 UTC by guilhermeprokisch

2024-09-05 22:48 UTC, Colonial-Dev commented on src/formatter/terminal_themed.rs
> +    stdout: RefCell<StandardStream>,
`RefCell<T>` isn't `Send` or `Sync` (that is, multi-thread-compatible) like `Arc<T>` is.

For something like this, you *probably* don't want to be writing to standard output/error from multiple threads anyways, so I would just do something like:

```rs
#[derive(Debug, Clone)]
pub struct Terminal {
    theme: Theme,
    stream: StandardSteam
}
```

2024-09-05 22:49 UTC, Colonial-Dev commented on src/formatter/terminal_themed.rs
> +pub struct TerminalFormatter {
I would change this to just be `Terminal`, similar to how the basic HTML formatter is just called `Html`.

2024-09-05 22:52 UTC, Colonial-Dev commented on src/formatter/terminal_themed.rs
> +            stdout: RefCell::new(StandardStream::stdout(ColorChoice::Always)),
I wouldn't assume that users want standard output - consider something like printing code snippets in a backtrace to standard error. Maybe take a `StandardStream` as one of the parameters.

2024-09-05 22:55 UTC, Colonial-Dev commented on src/formatter/terminal_themed.rs
> +                stdout.flush()?;
I would implement `finish` and call `flush` in there - doing it for every event could get mighty expensive (unless the immediacy is important to your use case.)

2024-09-05 22:57 UTC, Colonial-Dev requested changes
Pretty good, thank you! I don't see any bugs, just a few things that need tweaking.

2024-09-06 07:20 UTC, guilhermeprokisch commented
@Colonial-Dev, I have addressed some of your reviews. Please take a look and let me know if it meets your approval now. I have also added an example folder demonstrating how to use it, making it easy to see the results by running cargo run --example terminal_highlight. Additionally, I have included a theme generator. Frankly, this was the most challenging part, in my opinion. I believe that shipping with some built-in themes would be better.

2024-09-09 00:43 UTC, Colonial-Dev approved these changes

2024-09-09 01:08 UTC, Colonial-Dev commented
Looks good to me!

> I believe that shipping with some built-in themes would be better.

Yeah, I feel you. The Helix theme support is almost done!

2024-09-09 01:09 UTC, merged

2024-09-09 18:01 UTC, guilhermeprokisch commented
@Colonial-Dev  Btw I'm building a project based on this feature 

https://github.com/guilhermeprokisch/see/

Anything I'm here to help inkjet maintenance